// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozsvlaqpgaosjcfenhco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96c3ZsYXFwZ2Fvc2pjZmVuaGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTMzMTIsImV4cCI6MjA2MTA2OTMxMn0.N82s36u2cU5MT0ApTFqbbTxTan-uqPtXs4BRvalvypo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);